explosion/projects

- benchmarks/ud_benchmark/.gitignore
- benchmarks/ud_benchmark/README.md
- benchmarks/ud_benchmark/project.yml
- benchmarks/ud_benchmark/scripts/conll18_ud_eval.py
- benchmarks/ud_benchmark/scripts/evaluate.py
UD v2.5 pipeline with tagger, morphologizer and parser. Evaluate using the CoNLL 2018 shared task evaluation script.
> Add initial version of UD benchmark

- tutorials/nel_emerson/configs/nel.cfg
- tutorials/nel_emerson/project.yml
Following https://github.com/explosion/spaCy/pull/6216
> Update NEL tutorial

- benchmarks/ner_conll03/.gitignore
- benchmarks/ner_conll03/README.md
- benchmarks/ner_conll03/project.yml
- benchmarks/ner_conll03/requirements.txt
- benchmarks/parsing_penn_treebank/README.md
- benchmarks/parsing_penn_treebank/project.yml
- benchmarks/parsing_penn_treebank/requirements.txt
* remove unused `init_config` command
* fix `init vectors` command
* add `install` command for `spacy-lookups-data`
* add example variants file (used in `transformer.cfg`)
> Update benchmark projects

- pipelines/README.md
- pipelines/ner_demo/project.yml
- pipelines/ner_demo_replace/project.yml
- pipelines/ner_demo_update/project.yml
- pipelines/textcat_demo/project.yml
- pipelines/textcat_multilabel_demo/project.yml
* Use lang var in package name
* Update titles and descriptions
> Minor adjustments to NER and textcat demos

- pipelines/ner_wikiner/README.md
- pipelines/ner_wikiner/project.yml
- tutorials/nel_emerson/README.md
- tutorials/nel_emerson/configs/nel.cfg
- tutorials/nel_emerson/project.yml
- tutorials/nel_emerson/scripts/create_kb.py
- tutorials/nel_emerson/scripts/el_recipe.py
- tutorials/rel_component/scripts/rel_model.py
- NEL Prodigy annotation upgrade to spaCy v3 / Prodigy nightly
- remove redundant `init-config` from `ner_wikiner`
> Update NEL prodigy script

- tutorials/textcat_goemotions/README.md
Update readme instructions to latest spacy v3
> Fix textcat_goemotions readme

- pipelines/ner_demo_replace/project.yml
- pipelines/ner_demo_replace/scripts/create_config.py
- pipelines/ner_demo_update/project.yml
- pipelines/ner_demo_update/scripts/create_config.py
* use `spacy.copy_from_base_model.v1`
* use `replace_listeners` when sourcing the component that should be
updated
> Update NER demos for v3.0.6

- tutorials/nel_emerson/notebooks/notebook_video.ipynb
- tutorials/nel_emerson/project.yml
cf title, fixes https://github.com/explosion/spaCy/issues/7952
> update NEL notebook to v3

- azure-pipelines.yml
- benchmarks/ner_conll03/configs/cnn_glove_small.cfg
- benchmarks/ner_conll03/configs/transformer.cfg
- benchmarks/parsing_penn_treebank/configs/cnn_glove_small.cfg
- benchmarks/parsing_penn_treebank/configs/transformer.cfg
- integrations/huggingface_hub/configs/config.cfg
- integrations/ray/configs/default.cfg
- pipelines/ner_wikiner/configs/default.cfg
- pipelines/tagger_parser_ud/configs/default.cfg
- tutorials/nel_emerson/configs/nel.cfg
- tutorials/ner_drugs/configs/config.cfg
- tutorials/ner_fashion_brands/configs/config.cfg
- tutorials/ner_pytorch_medical/configs/spacy_config.cfg
- tutorials/textcat_goemotions/project.yml
> avoid W113 warning

- tutorials/textcat_goemotions/meta.json
- tutorials/textcat_goemotions/project.yml
- tutorials/textcat_goemotions/requirements.txt
- Changed name to **textcat_goemotions**
- Added `--build wheel` and `--meta-path` to **`package`** command
- Added `meta.json` with `spacy-transformers` requirement
- Added `spacy-transformers` as requirement in `requirements.txt`
Update
> Update transformer requirements in meta

- integrations/wandb/scripts/sweep.yml
Sorry to open another PR for this.
This is a small fix to a broken sweeps config merged in #74.
> Fix wandb sweep.yml config

- pipelines/floret_fi_core_demo/RESULTS.md
- pipelines/floret_fi_core_demo/requirements.txt
- pipelines/floret_ko_ud_demo/RESULTS.md
- pipelines/floret_ko_ud_demo/requirements.txt
- pipelines/floret_vectors_demo/requirements.txt
* Update `floret` requirements
* Update results for corrected `dim` and `hashCount` settings
> Update floret demo projects for floret module 0.10.1

- integrations/wandb/scripts/sweeps_using_code.py
- integrations/wandb/scripts/sweeps_using_config.py
Ref: https://github.com/explosion/spaCy/discussions/10097
Additionally, I formatted the affected code with black
> Fix directory creation problem in WandB example

- pipelines/tagger_parser_ud/project.yml
ref: https://github.com/explosion/spaCy/pull/10187
> Use multiline yaml syntax in UD project.yml

- pipelines/coref/project.yml
- pipelines/coref/scripts/run_eval.py
For simplicity I thought it makes sense to avoid having to raise the limit in the `conll` scripts, plus we can get rid of them. For this project the `lea` could be enough and we could decide later to add more evaluation metrics.
> LEA only evaluation

- azure-pipelines.yml
- run-tests.sh
Run tests only for those projects changed in the latest commit.
Tests are run via a script extracting the latest changes with `git diff`. `pytest` is then called once for each modified top-level directory.
Enhancement.
>  Run tests only in changed second-level directories

- pipelines/tagger_parser_ud/project.yml
Adds `check_requirements: true` to `pipeline/tagger_parser_ud/project.yml` ([context](https://github.com/explosion/spaCy/pull/11226#discussion_r968570291)).
> Add `check_requirements` to tagger_parser_ud/project.yml

- benchmarks/nel/requirements.txt
BuildKite test runs for the NEL benchmark fail due to the wrong dependency being specified (`pysqlite3` instead of `pysqlite3-binary`). This updates `requirements.txt` accordingly. With this change [BuildKite runs execute successfully](https://buildkite.com/explosion-ai/raphaels-projects-pipeline/builds/3#0183c1ce-072a-4e32-9282-8a481b3a2c04).
Fix.
> NEL benchmark: Fix pysqlite dependency

- benchmarks/nel/scripts/datasets/download_mewsli-9.sh
After a [recent upstream change in the `google-research` repo](https://github.com/google-research/google-research/commit/f324eb40813f0980553f934d6d07a6cd639f953c) setting up the venv for compiling the Mewsli-9 dataset didn't work anymore. This pins the SVN revision to sparsely checkout/`svn export` the most recent version before this changes.
Fix.
> NEL benchmark: pin repo revision for Mewsli-9 source

- benchmarks/nel/configs/nel.cfg
- benchmarks/nel/project.yml
- benchmarks/nel/scripts/candidate_generation/base.py
- benchmarks/nel/scripts/candidate_generation/embeddings.py
- benchmarks/nel/scripts/clean_data.py
- benchmarks/nel/scripts/compare_evaluations.py
- benchmarks/nel/scripts/compile_corpora.py
- benchmarks/nel/scripts/create_kb.py
- benchmarks/nel/scripts/datasets/dataset.py
- benchmarks/nel/scripts/datasets/evaluation.py
- benchmarks/nel/scripts/datasets/mewsli_9.py
- benchmarks/nel/scripts/datasets/utils.py
- benchmarks/nel/scripts/evaluate.py
- benchmarks/nel/scripts/train.sh
- Considers run name in storage of trained models so that new runs don't overwrite artifacts of prior runs.
- Smaller improvements (comments, logging) and fixes (e.g. number of docs was erroneously capped to 50 in `compile_corpora`).
Enhancement, fix.
> NEL benchmark: store model artifacts by run

- experimental/coref/requirements.txt
The coref project uses a bare URL to fetch a language model. `pkg_resources` doesn't handle that correctly when checking requirements - prefixing the bare URL with `NAME @` is necessary. Closes https://github.com/explosion/spaCy/issues/11733.
Bug fix.
> coref: Modify language Model URL to avoid pkg_resources fail

- tutorials/textcat_goemotions/README.md
- tutorials/textcat_goemotions/project.yml
Figured I'd add a disclaimer. It's a great tutorial to show how a CSV works, but it's not a model I'd be comfortable putting into production.
> GoEmotions disclaimer

- azure-pipelines.yml
- run-tests.sh
This updates the CI Python version from 3.7 to 3.9 because 3.7 will reach end of life next year. 
chore
> Update Python version for CI to 3.9

- azure-pipelines.yml
- run-tests.sh
Reverts explosion/projects#158 after noticing issues in the modified test script. (Most of) these changes may be reintroduced at a later point, after fixing those issues.
Fix.
> Revert "Update Python version for CI to 3.9"

- benchmarks/nel/README.md
- benchmarks/nel/project.yml
- benchmarks/nel/requirements.txt
- run-tests.sh
* Add `spacy_version` requirement
* Sync README
* Add temporary `spacy` requirement until #121
Bug fix of sorts.
> Update benchmarks/nel for spacy<3.5.0

- pipelines/floret_wiki_oscar_vectors/README.md
Update README for floret_wiki_oscar_vectors
Docs.
> Update README for floret_wiki_oscar_vectors

- experimental/ner_wikiner_speedster/test_project_ner_wikiner_speedster.py
Windows tests are failing due `capture=True` and output that's not UTF-8. This is to test whether you can keep `capture=True` if you provide the expected encoding, otherwise it seems like the best option is to use `capture=False`.
Tests.
> Remove capture from speedster tests

- .github/workflows/build-docs.yml
This was commented out to speed up the review process for #160, but accidentally left in even after #166 was merged.
minor meta fix?
> Enable generating projects.jsonl in auto doc build

- benchmarks/nel/project.yml
- benchmarks/nel/requirements.txt
The `benchmarks/nel` tests are currently [failing](https://buildkite.com/explosion-ai/raphaels-projects-pipeline/builds/12#0185f258-c565-4b68-aea2-1d9a84705306) on BuildKite. This fixes the issue by installing `pysqlite3` and upstream changes in `wikid` that have to be merged as well (https://github.com/explosion/wikid/pull/10, https://github.com/explosion/wikid/pull/9).
Bug fix.
> Fix `benchmarks/nel` test on BuildKite

- tutorials/nel_emerson/project.yml
- tutorials/nel_emerson/requirements.txt
- tutorials/nel_emerson/scripts/create_kb.py
From spaCy 3.5 onwards, `KnowledgeBase` is an abstract class
update
> use InMemoryLookupKB for spacy 3.5

- benchmarks/nel/requirements.txt
Update `requirements.txt` in NEL benchmark.
Fix.
> Fix NEL benchmark requirements

- benchmarks/speed/requirements.txt
Update flair requirement for benchmarks/speed
?
> Update flair requirement for benchmarks/speed

- requirements.txt
Default to spacy v3.5 for repo tests.
?
> Default to spacy v3.5

- .github/workflows/tests.yml
> Fix fetch depth for CI test script

- benchmarks/nel/requirements.txt
- benchmarks/nel/scripts/candidate_generation/embeddings.py
Replace deprecated levenshtein method in NEL benchmark.
Bug fix.
> Replace deprecated levenshtein method in NEL benchmark

- run-tests.sh
Now that torch has a number of dependencies which means it shouldn't be simply uninstalled.
CI.
> Remove excludes when cleaning up environments

- benchmarks/speed/requirements.txt
This reverts commit dadc36dcb26d9349282341d0f0fb801cbeec1477. This didn't actually fix the problem, which is restricted to python 3.8.0 and python 3.8.1.
?
> Revert "Add torch constraint to speed benchmark (#195)"

- tutorials/spanruler_restaurant_reviews/.gitignore
Ensure that files in the `spanruler_restaurant_reviews/assets` folder are Git ignored.
fix
> add assets dir to gitignore

- nel-wikipedia/README.md
Refer to v3 projects for Wikidata processing.
docs update
> Refer to v3 version
