integrations/wandb/README.md
integrations/wandb/project.yml
integrations/wandb/scripts/customize_configs.py
integrations/wandb/scripts/run_configs.py

The latest spaCy v3 RC doesn't have the `train` function in `spacy.cli.train` anymore - updating the code here accordingly.

Update train call in W&B project

---

tutorials/textcat_goemotions/configs/bert.cfg
tutorials/textcat_goemotions/configs/cnn.cfg

As I was testing this out, I realized that it was using the incorrect factory for this multilabel dataset.

fix textcat_goemotions textcat factory

---

tutorials/textcat_goemotions/project.yml

Hello folks!
I was testing the text_cat_goemotions project. And the init-vectors command was not working.
It was throwing the following message: `Error: No such command 'model'.`
I noticed that the command changed (https://spacy.io/api/cli#init-vectors),
so I modified it accordingly. Seems to be working now.

fix: Fix text_cat_goemotions project init-vectors

---

benchmarks/speed/requirements.txt

I assume this got committed by accident when running the project before? (cf https://github.com/explosion/projects/commit/0403ebd2e0a826d526c4bd462e5dda60ea92d6d4)

remove cupy-cuda102 requirement

---

pipelines/tagger_parser_ud/README.md
pipelines/tagger_parser_ud/project.yml

Docs refer to `preprocess` but it was called `convert` here.
Also removed a stale comment.

Change command name to match docs

---

tutorials/textcat_goemotions/project.yml

When running the `textcat_goemotions` example via `python -m spacy project run all` on Windows 10, the creation of the `training` directory causes an error due to the path structure on windows. The change in this PR uses python `os.makedir` to create the directory to make it OS agnostic. This is my first time contributing to this repo, so please let me know if there are any additional contributor gates I need to follow. Thanks.  
The log of the original error seen is below:
```
ℹ Running workflow 'all'
================================= preprocess =================================
ℹ Skipping 'preprocess': nothing changed
=================================== train ===================================
Running command: mkdir -p training/cnn
Traceback (most recent call last):
File …
```

textcat_goemotions - creation of training directory on Windows causes error

---

benchmarks/ner_conll03/project.yml

In the CoNLL-03 named entity recognition benchmark, the test corpus is saved as `test.spacy` but it's later called as `testb.spacy` during the evaluation, which makes it fail. This PR fixes this issue.

Change testb.spacy to test.spacy so ner benchmark works

---

tutorials/textcat_goemotions/scripts/convert_corpus.py

Allows custom .tsv datasets with some unlabeled data points to be processed by read_tsv function. If there is a text classification dataset where for one or more data points, no labels apply (and no dummy label has been generated for N/A), this allows those to be processed using the spacy projects run preprocess command.

Allow data in tsv with no labels

---

integrations/streamlit/project.yml

The spaces cause this to not work on the command line. See:
https://github.com/explosion/spaCy/issues/8662

Remove spaces from list of models

---

azure-pipelines.yml

Projects that include `package` with `--build-wheel` in their workflow, fail the azure tests because `wheel` is not installed
- Add `wheel` as dependency in the `azure-pipeline.yml`

Add wheel to azure-pipelines.yml

---

azure-pipelines.yml
experimental/ner_spancat/project.yml
tutorials/textcat_goemotions/project.yml

Revert PR https://github.com/explosion/projects/pull/42 - cf https://github.com/explosion/spaCy/issues/6957#issuecomment-872403914
We didn't actually need the `mkdir` statement there as `spacy train` takes care of this.
Adding 2 small fixes for spaCy versions here as well.

remove makedirs command that wasn't working

---

tutorials/rel_component/scripts/rel_pipe.py

A couple of users have gotten errors in relation extraction because their entities at runtime differ from those in their gold data. This is a fix indicated in [this issue](https://github.com/explosion/spaCy/discussions/9222#discussioncomment-1355925) that simply treats any pairs not mentioned in the gold data as wrong.

Fix issue with RelEx scoring

---

integrations/wandb/scripts/sweeps_using_code.py

This caused a `CommError` when run as is. Most likely caused by using an entity that did not match the API key provided which is the users own.

Remove `entity` from `wandb.sweep` call

---

benchmarks/ner_conll03/configs/cnn_glove_small.cfg
benchmarks/parsing_penn_treebank/configs/cnn_glove_small.cfg
benchmarks/textcat_architectures/configs/config_cmu_ensemble.cfg
benchmarks/textcat_architectures/configs/config_dbpedia_ensemble.cfg
benchmarks/textcat_architectures/configs/config_imdb_ensemble.cfg
experimental/ner_spancat/configs/spancat.cfg
integrations/huggingface_hub/configs/config.cfg
integrations/prodigy/configs/config.cfg
integrations/ray/configs/default.cfg
integrations/wandb/configs/default_config.cfg
pipelines/ner_wikiner/configs/default.cfg
pipelines/tagger_parser_ud/configs/default.cfg
tutorials/ner_drugs/configs/config.cfg
tutorials/ner_fashion_brands/configs/config.cfg
tutorials/textcat_goemotions/README.md
tutorials/textcat_goemotions/configs/cnn.cfg

Not tested, though I don't think this should break anything.
We may want to do this for some other old architectures too, but for now
I just focused on this one.
Inspired by https://github.com/explosion/spaCy/discussions/9815.

Update all configs to use Tok2Vec.v2 instead of v1

---

tutorials/ner_double/project.yml

Install `en_drugs` model with `--no-deps` to avoid spacy upgrades/downgrades.
Add `spacy_version` to `project.yml` to indicate compatibility.

Install ner_double en_ner_drugs model without deps

---

azure-pipelines.yml
pipelines/floret_wiki_oscar_vectors/README.md
pipelines/floret_wiki_oscar_vectors/project.yml
pipelines/floret_wiki_oscar_vectors/requirements.txt
pipelines/floret_wiki_oscar_vectors/scripts/concat_files.py
pipelines/floret_wiki_oscar_vectors/scripts/tokenize_resource.py
pipelines/floret_wiki_oscar_vectors/scripts/train_floret.py
pipelines/floret_wiki_oscar_vectors/test_floret_wiki_oscar_vectors.py

Add a user-friendly cross-platform floret vectors project for training on Wikipedia (using `wikiextractor`) + OSCAR (using `datasets`).
The project defaults use Macedonian to provide a small but realistic demo.
The tests override the defaults to use the much-smaller Yoruba data sources.

Add floret Wikipedia+OSCAR vectors project

---

tutorials/nel_emerson/README.md

This PR adjusts the paths specified in the sample command for being used directly after executing the workflow below.
Workflow:
```
python -m spacy project clone tutorials/nel_emerson
python -m spacy project assets /home/prodigy/nel_emerson
python -m spacy project run all
```

adjust paths in entity linker tutorial, fix file name

---

benchmarks/speed/requirements.txt

Due to new version with backwards incompatibilities being released yesterday. The new version breaks `spacy run download` in the speed  benchmark, since the latest `flair` version doesn't consider this yet.

Pin conllu version in speed benchmark

---

benchmarks/speed/project.yml
benchmarks/speed/requirements.txt
benchmarks/speed/scripts/run_nlp.py

Update speed benchmark for newer `spacy-transformers` and `flair` APIs.
Requires #119 for the tests to pass.

Update speed benchmark

---

benchmarks/textcat_architectures/requirements.txt
integrations/wandb/requirements.txt

Two example projects were pinning `ml_datasets` to exactly `0.2.0a0` even though we've had a `0.2.0` release since then.

Allow ml_datasets 0.2.0

---

benchmarks/nel/requirements.txt
benchmarks/nel/scripts/wiki/wiki_dump_api.py
benchmarks/nel/scripts/wiki/wikidata.py
benchmarks/nel/scripts/wiki/wikipedia.py

The weekly build currently fails on BuildKite to the usage of Python 3.7 and the `sqlite3` version shipped with it due to its lack of support of the SQLite upsert syntax used in the NEL benchmark project.
Since upgrading `sqlite3` isn't easily possible independent from the Python installation itself, this PR replaces `sqlite3` with the drop-in support `pysqlite3`.

Use pysqlite3 instead of sqlite3 to allow for support of upsert syntax in Python 3.7

---

pipelines/README.md
pipelines/spancat_demo/.gitignore
pipelines/spancat_demo/README.md
pipelines/spancat_demo/assets/.gitattributes
pipelines/spancat_demo/assets/dev.json
pipelines/spancat_demo/assets/train.json
pipelines/spancat_demo/project.yml
pipelines/spancat_demo/scripts/convert.py
pipelines/spancat_demo/test_project_spancat_demo.py
tutorials/README.md

cf. https://github.com/explosion/spaCy/discussions/9635, https://github.com/explosion/spaCy/discussions/11517, https://github.com/explosion/spaCy/discussions/11518
This PR adds a minimal `spancat_demo` project that demonstrates how to convert and train a `spancat` pipeline. It borrows heavily from the `ner_demo` project (the dummy data, command organization, etc.), with minimal changes (conversion script, config, etc.)
Enhancement

Add minimal spancat demo

---

benchmarks/speed/project.yml

In the speed benchmark project, the comment about the assets got moved away from the actual definition of the assets - putting it back for clarity for those reading the `yml` file manually ;-)

move comment on assets

---

tutorials/textcat_goemotions/README.md
tutorials/textcat_goemotions/configs/cnn_with_pretrained.cfg
tutorials/textcat_goemotions/project.yml

In the GoEmotions project, there was a section on combining components from a pretrained pipeline. The method used was including components in your training config but disabling them. But since we have `spacy assemble` now, that allows you to keep your training config unmodified, and just use a separate config for `assemble`. 
This rewrites that section fo the README to use `spacy assemble`. It includes a sample config for use with assemble and explains how to make a config like that for your own pipeline.

Change GoEmotions to use spacy assemble

---

pipelines/README.md
pipelines/edit_tree_lemmatizer/.gitignore
pipelines/edit_tree_lemmatizer/README.md
pipelines/edit_tree_lemmatizer/project.yml
pipelines/edit_tree_lemmatizer/test_project_etl.py

It looks like the [project](https://github.com/explosion/spacy-experimental/tree/v0.4.0/projects/edit_tree_lemmatizer) for the experimental edit-tree lemmatizer was removed when moving the functionality to spaCy. Moving it back to the "pipelines" directory here, as I think it's still a nice demo project to showcase how the lemmatizer trains/works.
Adjusted the project to refer to the `trainable_lemmatizer` component and tested to work with spaCy 3.5.
feature

Demo project for edit-tree lemmatizer

---

.github/workflows/build-docs.yml

This is a script to automatically run update scripts once a week, just like the autoblack job in spaCy.
Currently the config update script (`update_configs.py`) is not included. One reason is that config changes require more review, another is that there may be cases where we don't want configs auto-filled. Another reason is that currently the script just fails with an error on some projects, which needs to be checked separately.
automation

Add automatic doc building

---

benchmarks/nel/project.yml
benchmarks/nel/scripts/candidate_generation/base.py
benchmarks/nel/scripts/candidate_generation/embeddings.py
benchmarks/nel/scripts/candidate_generation/lexical.py
benchmarks/nel/scripts/compat.py
benchmarks/nel/scripts/custom_functions.py
benchmarks/nel/scripts/datasets/dataset.py
benchmarks/nel/scripts/datasets/evaluation.py

Recent [commits show CI failures](https://dev.azure.com/explosion-ai/Public/_build/results?buildId=23901&view=logs&j=f1d52934-b974-5ece-337e-e658a4411382&t=25745add-d8f1-5bdf-c7de-2e51e93603d8) caused by `wikid` importing `InMemoryLookupKB`.  This is unexpected, as this error has [been accounted for in `wikid` already](https://github.com/explosion/wikid/blob/main/scripts/create_kb.py#L12). 
The NEL benchmark itself hasn't been adjusted accordingly yet anyway, so this PR aims to support spacy>=3.0.0,<3.6.0 by relaxing the requirement in the project file and importing the correct KB class contingent on the spaCy version.
Fix.

NEL benchmark: update spaCy version

---

tutorials/rel_component/scripts/parse_data_generic.py

As this frequently comes up that users want to parse their REL data from Prodigy, I made a slightly more generic script that will guide users on how to do this.
We'll want to provide more built-in support in the future, but in the meantime this should already be useful.
new feature

Add more generic script for parsing REL

---

experimental/ner_spancat_compare/configs/ner_assemble.cfg
experimental/ner_spancat_compare/scripts/convert.py
experimental/ner_spancat_compare/scripts/transfer_ent_component.py

* Rename component to `transfer-ent` to avoid `.` in factory name (for spacy v3.4.2+)
* In convert script, make sure all spans belong to the same doc object when initializing span groups. Otherwise there can be cases where the span label is not in the doc vocab.
Bug fix.

Update ner_spancat_compare for newer spacy, doc/vocab issues
